### ISSUE TITLE
Run Radiance Analysis Node - File does not exist?

### ISSUE THREAD

**Issue by Mylarkid** [mostaphaRoudsari/ladybug#433]
I'm getting an error on this node looks like it's not writing the *.ill file that it needs? 

`Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "C:\Users\bfrederick\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\solaraccess\gridbased.py", line 380, in results
    analysisGrid.set_values_from_file(
  File "C:\Users\bfrederick\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\analysisgrid.py", line 252, in set_values_from_file
    if os.path.getsize(file_path) < 2:
  File "C:\Program Files (x86)\IronPython 2.7\Lib\genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
WindowsError: [Errno 2] file does not exist: c:/ladybug\dynamoTEST\solaraccess\result/dynamoTEST.ill
`

**Comment by mostaphaRoudsari** [comment]
Hi @Mylarkid, This issue should be posted to the forum. If you don't already have an account follow the directions here to create one: http://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8 

Please post it with a screenshot and under the dynamo category.
